language: cpp
compiler:
  - g++
sudo: required
dist: xenial

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential git scons libtool autoconf valgrind doxygen wget unzip
  - sudo apt-get install -y libboost-dev libboost-program-options-dev libboost-thread-dev uuid-dev libexpat1-dev libglib2.0-dev libsqlite3-dev libcurl4-gnutls-dev

install:
  - git clone https://github.com/iotivity/iotivity.git -b 1.2-rel
  - git clone https://github.com/01org/tinycbor.git iotivity/extlibs/tinycbor/tinycbor -b v0.4
  - sed -i "75i\        SConscript('csdk/stack/samples/linux/ocf_mylight/SConscript')" iotivity/resource/SConscript
  - git clone https://github.com/webispy/ocf_mylight -b oic_1.1 iotivity/resource/csdk/stack/samples/linux/ocf_mylight

script:
  - cd iotivity; scons -j4 RELEASE=True LOGGING=False
